Meteor.startup(function() {
   var userEmail = 'test@test.com'; 
   if(Meteor.users.find({'emails.address':userEmail}).count() == 0){
       var ownerId = Accounts.createUser({
           email:userEmail,
           password:'111111'
       });
       List.insert({
        sellerName:"上海承泰信息科技",
        buyerName:"上海供应商1",
        creditorAmount:"100",
        creditorDueDate:"2017-05-01",
        transType:"A类型",
        limitAmout:"50",
        approvedAmount:"50",
        owner:ownerId
    });
    List.insert({
        sellerName:"上海承泰信息科技",
        buyerName:"上海供应商2",
        creditorAmount:"110",
        creditorDueDate:"2017-05-02",
        transType:"C类型",
        limitAmout:"100",
        approvedAmount:"100",
        owner:ownerId
    });
    List.insert({
        sellerName:"上海承泰信息科技",
        buyerName:"上海供应商3",
        creditorAmount:"120",
        creditorDueDate:"2017-05-04",
        transType:"B类型",
        limitAmout:"90",
        approvedAmount:"90",
        owner:ownerId
    });
    List.insert({
        sellerName:"上海承泰信息科技",
        buyerName:"上海供应商4",
        creditorAmount:"130",
        creditorDueDate:"2017-05-05",
        transType:"A类型",
        limitAmout:"70",
        approvedAmount:"70",
        owner:ownerId
    });
    List.insert({
        sellerName:"上海承泰信息科技",
        buyerName:"上海供应商5",
        creditorAmount:"140",
        creditorDueDate:"2017-05-06",
        transType:"B类型",
        limitAmout:"60",
        approvedAmount:"60",
        owner:ownerId
    });
   }
});